### ISSUE TITLE
Incorrect highlighting

### ISSUE THREAD

**Issue by shds86** [ace-diff/ace-diff#53]
I have 2 version of a code with one different value of var:
left:
```
(function (window, $) {

    var sourceId, targetId, item,
        leftSource, rightSource,
        aceDiffer;
    $(document).ready(function () {
        sourceId = $("#source").val();
        targetId = $("#target").val();
        item = $("#item").val();

        aceDiffer = new AceDiff({
            element: '#diffs-container',
            mode: "",
            left: {
                editable: false,
                copyLinkEnabled: false,
                content: ''
            },
            right: {
                editable: false,
                copyLinkEnabled: false,
                content: ''
            }
        });

})(window, jQuery);
```
right:
```
(function (window, $) {

    var sourceId, targetId, item,
        leftSource, rightSource,
        aceDiffer;
    $(document).ready(function () {
        sourceId = $("#source").val();
        targetId = $("#target").val();
        item = $("#item").val();

        aceDiffer = new AceDiff({
            element: '#diffs-container',
            mode: "",
            left: {
                editable: false,
                copyLinkEnabled: true,
                content: ''
            },
            right: {
                editable: false,
                copyLinkEnabled: false,
                content: ''
            }
        });

})(window, jQuery);
```

The diff is in left.copyLinkEnabled, left code has `false`, right has `true` but ace-diff marks the next line of the editors like it has the diff. Where is the issue?

**Comment by shds86** [comment]
![image](https://user-images.githubusercontent.com/1191408/44333966-ff3cb700-a478-11e8-90ac-9baae4045b67.png)

**Comment by nitslucky** [comment]
Did you find solution?

**Comment by shds86** [comment]
Unfortunately I have not found solution. Too many ace specific and ace-diff specific moments have been found. I use ace v1.2.6

**Comment by JackuB** [comment]
Don't have an example to repro, but a bunch of similar issues were solved by PR #69 - closing this one as well. Feel free to reopen

**Comment by Jeff534** [comment]
Same issue here. Is there a plan when the fix could be merged?

**Comment by Nicky-G1** [comment]
It seems like this is still an issue and something I am running into trying to implement this. It doesn't seem to handle nested XML documents very well. Most times the change highlighting is off by a line or incorrect by a decent margin. Example below using the demo website using the latest versions.

![image](https://github.com/ace-diff/ace-diff/assets/142953273/0bd0c291-e245-42d8-ba8e-fcc1dc141bae)

I used a demo page off the diff-match-patch to sort of see what the underlying diff could look like and it seems to generate the diff correctly.

https://neil.fraser.name/software/diff_match_patch/demos/diff.html
![image](https://github.com/ace-diff/ace-diff/assets/142953273/a2ca6248-97ce-43e9-8d74-3db9ad875f67)

It appears as though ( just a guess ), that something is not working correctly with the visualization portions in some cases.

Has anyone else run into this and found a working solution ?
